language: python
python:
    - "3.4"
    - "3.5"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test  # coreir (for g++-4.9)
    packages:
      - g++-4.9  # coreir

before_install:
    - pip install --upgrade pip setuptools

    # BEGIN: coreir installation
    - git clone -b dev https://github.com/rdaly525/coreir.git
    - cd coreir
    - export COREIRCONFIG="g++-4.9"
    - export COREIR=$PWD
    - sudo make install
    - pip install git+git://github.com/leonardt/pycoreir.git
    - cd ..
    # END: coreir installation
    - git clone -b coreir-dev https://github.com/phanrahan/magma.git
    - pip install -e magma

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install fabricate
    - pip install -e .

script:
    - py.test --cov=mantle tests/
