language: python
python:
    - "3.6"

before_install:
    - git clone https://github.com/phanrahan/magma.git
    - pip install -e magma
    - source magma/.travis/install_coreir.sh

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install fabricate
    - pip install -e .

script:
    - py.test --cov=mantle tests/
