language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test  # for gcc-4.9
    - sudo apt-get -qq update
    - pip install --upgrade pip setuptools
    - sudo apt-get install -y g++-4.9 gcc-4.9  # coreir dependency

    # BEGIN: coreir installation
    - git clone -b dev https://github.com/rdaly525/coreir.git
    - cd coreir;
    - export COREIRCONFIG="g++-4.9";
    - export COREIR=$PWD
    - export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH
    - make install
    - make py
    - cd ..;
    # END: coreir installation

install: 
    - pip install -r requirements.txt
    - git clone git@github.com:phanrahan/magma.git
    - pip install -e magma
    - git clone git@github.com:phanrahan/loam.git
    - pip install -e loam
    - pip install pytest-cov
    - pip install fabricate
    - pip install -e .

script: 
    - py.test --cov=mantle --ignore=coreir/  # Ignore tests in the coreir directory
    # Run bake verilog tests
    - cd tests/verilog
    - . doit
    - cd ${TRAVIS_BUILD_DIR}
